name: hopewater
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  sizer: ^2.0.15
  google_fonts: ^6.2.1
  get: ^4.6.6
  provider: ^6.1.2
  smooth_page_indicator: ^1.1.0
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  firebase_storage: ^12.0.0
  fluttertoast: ^8.2.6
  flutter_launcher_icons: ^0.13.1
  shared_preferences: ^2.2.3
  firebase_messaging: ^15.0.0
  firebase_database: ^11.0.0
  image_picker: ^1.1.2
  shimmer: ^3.0.0
  persistent_shopping_cart: ^0.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/app_icon.jpg"
  adaptive_icon_background : "0xff5DCCFC"
  remove_alpha_ios: true
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/
