// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfjuydlbzvQmFQRncLEpoArulbqe63Fwk',
    appId: '1:233510579068:web:3b2b8bbb55463d189352f9',
    messagingSenderId: '233510579068',
    projectId: 'hope-water-1945d',
    authDomain: 'hope-water-1945d.firebaseapp.com',
    storageBucket: 'hope-water-1945d.appspot.com',
    measurementId: 'G-5D3299Q6B5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHtdAYP9SmZIlnJTydP31j4JIdGBNj0WY',
    appId: '1:233510579068:android:a6addda67b52a0b69352f9',
    messagingSenderId: '233510579068',
    projectId: 'hope-water-1945d',
    storageBucket: 'hope-water-1945d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrakRPZZnyiYRYrdNtI5sa-ln_Rl2UoJg',
    appId: '1:233510579068:ios:c8f940b298996fa59352f9',
    messagingSenderId: '233510579068',
    projectId: 'hope-water-1945d',
    storageBucket: 'hope-water-1945d.appspot.com',
    iosBundleId: 'com.example.hopewater',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrakRPZZnyiYRYrdNtI5sa-ln_Rl2UoJg',
    appId: '1:233510579068:ios:c8f940b298996fa59352f9',
    messagingSenderId: '233510579068',
    projectId: 'hope-water-1945d',
    storageBucket: 'hope-water-1945d.appspot.com',
    iosBundleId: 'com.example.hopewater',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfjuydlbzvQmFQRncLEpoArulbqe63Fwk',
    appId: '1:233510579068:web:d90f9ffbf53cef1e9352f9',
    messagingSenderId: '233510579068',
    projectId: 'hope-water-1945d',
    authDomain: 'hope-water-1945d.firebaseapp.com',
    storageBucket: 'hope-water-1945d.appspot.com',
    measurementId: 'G-CRBRQWD3WS',
  );
}
